const colors = {
  light: {
    text: "#0a0a1a",
    tint: "#4f8ef7",
    background: "#f8f9ff",
    foreground: "#0a0a1a",
    card: "#ffffff",
    cardForeground: "#0a0a1a",
    primary: "#4f8ef7",
    primaryForeground: "#ffffff",
    secondary: "#f0f4ff",
    secondaryForeground: "#1a1a2e",
    muted: "#f0f4ff",
    mutedForeground: "#6b7280",
    accent: "#a855f7",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e9f5",
    input: "#e5e9f5",
    success: "#22c55e",
    successForeground: "#ffffff",
  },
  dark: {
    text: "#f0f0ff",
    tint: "#4f8ef7",
    background: "#0a0a1a",
    foreground: "#f0f0ff",
    card: "#13132b",
    cardForeground: "#f0f0ff",
    primary: "#4f8ef7",
    primaryForeground: "#ffffff",
    secondary: "#1a1a35",
    secondaryForeground: "#d0d0f0",
    muted: "#1a1a35",
    mutedForeground: "#8888aa",
    accent: "#a855f7",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e1e3f",
    input: "#1e1e3f",
    success: "#22c55e",
    successForeground: "#ffffff",
  },
  radius: 16,
};

export default colors;
